# Generated by Django 3.1.3 on 2021-04-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=9, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('RECEPTIONIST', 'receptionist'), ('DOCTOR', 'doctor'), ('PATIENT', 'patient')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('extra_data', models.CharField(blank=True, max_length=4096, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('CANCELLED', 'cancelled'), ('ACTIVE', 'active'), ('DONE', 'done')], default='ACTIVE', max_length=20)),
                ('prescription', models.CharField(blank=True, max_length=3000, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='core.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='core.user')),
            ],
        ),
    ]
