# Generated by Django 3.1.3 on 2021-04-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_specialty',
            field=models.CharField(blank=True, choices=[('CARDIOLOGIST', 'Cardiologist'), ('OPHTALMOLOGIST', 'Ophtalmologist'), ('DERMATOLOGIST', 'Dermatologist'), ('ONCOLOGIST', 'Oncologist'), ('PEDIATRICIAN', 'Pediatrician')], max_length=20, null=True),
        ),
    ]
